### ISSUE TITLE
Configuring keyboard shortcuts

### ISSUE THREAD

**Issue by enterprisey** [mortalis13/Close-Tabs-Shortcuts-XPI#1]
Thanks for the wonderful addon! I was wondering if there are any plans to allow users to configure the keyboard shortcuts that this addon provides, or whether we could do this already.

**Comment by mortalis13** [comment]
For now there is no possibility to change shortcuts from an options page (at least I haven't found it). So the shortcuts are static.
It's easy to change them in the source code. But to install the changed addon you should use the Nightly edition of Firefox, which allows to install unsigned addons.
The shortcuts are in the `manifest.json` file of the code. So it's just need to be packed as a zip archive and the extension changed to .xpi.

Or I could create an alternative install (XPI file) and sign it separately with the Mozilla service. It could be installed in the stable Firefox release. Or you could register on the Mozilla Addons site and submit the change addon so it's signed. It would be an addon just visible and accessible to you (there is an option for that). So you can experiment with it later.

If you need more details on any of these options tell me and I'll explain it.

**Comment by enterprisey** [comment]
I was searching around and found out about https://github.com/mikecrittenden/shortkeys, which looks like it lets you configure the shortcuts. Unfortunately, it looks like the architecture of the extension would have to change a bit, since the shortkeys solution is to run a script on page load that handles the dynamically-loaded keyboard shortcuts. I imagine this can't be good for performance, so I'm fine whether or not this change is made. Also, thanks for the quick response!

**Comment by kstev99** [comment]
Love this add-on, does just what I have been looking for.  I was using Saka Key with shortcut ALT+A to close tabs to the right.  I am using Nightly Firefox and tried your suggestion of editing the manifest.json within the downloaded xpi file to change the keyboard shortcut.  Alt+SHift+F2 just seemed too awkward.  I used Notepad++ and every time I try re-installing the modified .xpi, it says the the add-on is corrupt.  I am not changing the structure of the file only changing { "default": "Alt+Shift+F2" } to { "default": "Alt+A" }.

What am I doing wrong?  I also found the xpi file that was placed in the profile\xxxx\extensions folder after install and tried editing that manifest.xpi but it had no effect on the keyboard shortcut

**Comment by mortalis13** [comment]
Hi.
In Nightly there's a config parameter which blocks unsigned addons by default.
Try this:
- type `about:config?filter=xpinstall.signatures.required` into the address bar
- change the config to `false`

**Comment by kstev99** [comment]
I'd already checked this and it is set to False.  Thanks

**Comment by mortalis13** [comment]
ok, checked the addon modification in Nightly.
`.xpi` file has to be named according to the addon `id`, it's a manifest key.
It's not mandatory for published addons so I didn't include it. During development I was testing it with `about:debugging` and **Load Temporary Add-on** command in Nightly so it didn't generate this problem.

So the steps to modify an addon:
- download the addon code from this repository (I updated the manifest so it has an ID, later will upload new version on Mozilla)
- unzip (7-Zip), open manifest in a text editor
- change it, change `id` field for any text (it's usually name@company)
- zip all files to a zip archive (so that manifest file is in the root of the archive)
- rename it to "**`id`.xpi**"
- put it to **extensions** folder of Firefox profile
- open Nightly, navigate to **about:addons**, enable the addon

You may test the addon with the mentioned **Temporary** load command to prevent repacking the files on every change.

**Comment by kstev99** [comment]
This helps, thank you for your time.

**Comment by Flnch** [comment]
So, I found two ways the keyboard shortcuts can be changed:

- One could program a settings page for the extension that triggers a [`commands.update()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands/update) to update the shortcut. However, this is unnecessary work, see the next option.
- Use Firefox's built in extension shortcut setting:
  1. Open `about:addons`
  2. Click on the gear symbol, then on `Manage Extension Shortcuts`.  
  ![manageExtensions](https://user-images.githubusercontent.com/33035992/74015379-cbb55b80-4990-11ea-8eb6-27ac4d927596.png)
  3. Change the shortcuts to your favor!  
  ![manageExtensionShortcuts](https://user-images.githubusercontent.com/33035992/74015435-eab3ed80-4990-11ea-8276-ef8ae066fea4.png)

@mortalis13 Maybe handy to mention this possibility in the [extension's description](https://addons.mozilla.org/en-US/firefox/addon/close-tabs-shortcuts/)?

**Comment by mortalis13** [comment]
Really cool!
It's a long time I haven't checked Firefox changelogs.
Seems this feature appeared in the v66.
Appreciate it, thanks a lot!
