### ISSUE TITLE
Close others would close pinned tabs

### ISSUE THREAD

**Issue by NightRare** [mortalis13/Close-Tabs-Shortcuts-XPI#3]
Thanks for the helpful add-on.

Just one thing that even pinned tabs will be closed when "close others". I am not sure whether this is designed intentionally, however this does not share the same behaviour as clicking on "Close other tabs" on the context menu of a tab.

So would you please fix it (or add another option maybe)? Thank you.

**Comment by mortalis13** [comment]
Hi. You're right, the pinned tabs should remain pinned. Please check the version 1.1.7 of the addon.
Thanks.

**Comment by NightRare** [comment]
Cool, thanks.
