### ISSUE TITLE
Option to change shortcuts doesn't appear (Firefox 80.0a1)

### ISSUE THREAD

**Issue by Caspid** [mortalis13/Close-Tabs-Shortcuts-XPI#6]
"Starting from Firefox v66 these shortcuts can be changed in the Add-ons Manager (Ctrl+Shift+A) selecting the Manage Extension Shortcuts menu in the page settings."  After clicking Manage, no Options tab appears for changing shortcuts.

**Comment by Cognitohazard** [comment]
It's in the "manage extension shortcuts" page accessed from the cog icon.

**Comment by mortalis13** [comment]
Right, the "Manage Extension Shortcuts" is for all your addons that have configurable shortcuts, so you open it from the Addon Manager settings, not from the individual addon page.

**Comment by Caspid** [comment]
I found it, thank you!
