### ISSUE TITLE
No option to change shortcut keys

### ISSUE THREAD

**Issue by kstev99** [mortalis13/Close-Tabs-Shortcuts-XPI#7]
Using Firefox Nightly 80.01 I see no option to change the shortcut keys.  Only "Manage" but no "Manage Extension Shortcuts" in the menu

**Comment by mortalis13** [comment]
You should click on the Addon Manager settings icon (the cog icon in the top-right corner), it's the global addons settings menu, for all addons.
So the "Manage Extension Shortcuts" page will list all your addons that have shortcuts and you change just the addon you need.
I'll link another related issue: #6.

**Comment by kstev99** [comment]
Thanks for your help.  I looked right over it
